#cloud-config

write_files:
  - path: /root/join-swarm.sh
    permissions: 0755
    content: |
      #!/bin/bash
      # make sure there's no disk state that points to an existing swarm
      docker swarm leave
      # get the swarm worker token
      TOKEN=$(wget -nv -q -O - --retry-connrefused 10 --waitretry 5 http://master0:1337/join/worker)
      docker swarm join --token $TOKEN master0:2377
  - path: /root/leave-swarm.sh
    permissions: 0755
    content: |
      #!/bin/bash
      HOSTNAME=$(hostname)
      # signal the master to drain services from our node
      wget -nv -q -O - --retry-connrefused 10 --waitretry 5 http://master0:1337/drain/$HOSTNAME
      docker swarm leave
  - path: /etc/systemd/system/swarm-join.service
    permissions: 0444
    content: |
      [Unit]
      Description=Join Swarm
      DefaultDependencies=no
      After=multi-user.target
      [Service]
      Type=oneshot
      ExecStart=/root/join-swarm.sh
      [Install]
      WantedBy=multi-user.target
  - path: /etc/systemd/system/swarm-leave.service
    permissions: 0444
    content: |
      [Unit]
      Description=Leave Swarm
      DefaultDependencies=no
      Before=shutdown.target reboot.target halt.target
      [Service]
      Type=oneshot
      ExecStart=/root/leave-swarm.sh
      [Install]
      WantedBy=halt.target reboot.target shutdown.target

apt:
  sources:
    docker.list:
      source: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
      keyserver: p80.pool.sks-keyservers.net
      keyid: 58118E89F3A912897C070ADBF76221572C52609D

apt_update: true
#apt_upgrade: true

packages:
  - ntp
  - docker-engine
  #- tmux
  #- htop
  #- vim
  - fail2ban
  - apt-file
  - gcc
  - make
  - libc-dev
  - vim
  #- curl

runcmd:
  - usermod -G docker cluster
  - wget -P /tmp http://us.download.nvidia.com/XFree86/Linux-x86_64/367.57/NVIDIA-Linux-x86_64-367.57.run
  - sudo sh /tmp/NVIDIA-Linux-x86_64-367.57.run --silent
  - wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.0-rc.3/nvidia-docker_1.0.0.rc.3-1_amd64.deb
  - sudo dpkg -i /tmp/nvidia-docker*.deb && rm /tmp/nvidia-docker*.deb
  - systemctl enable docker
  - systemctl enable swarm-join
  - systemctl enable swarm-leave
  - systemctl start docker
  - systemctl start swarm-leave
  - systemctl start swarm-join
  - sudo mkdir /fathom
  - sudo mount -t cifs //swarmdemostore.file.core.windows.net/swarm-demo-fileshare /fathom -o vers=3.0,user=swarmdemostore,password=hFlNNLV5HavxqyMd8IlVutRpScHxyPzBpN/y3oqFEFIQ5ir9FGZGxnwOKSUbNQAL7/zS0RDI2S92qDEovm+Q5A==,dir_mode=0777,file_mode=0777
  #- reboot
