#cloud-config

write_files:
  - path: /root/swarm-helper.py
    permissions: 0755
    content: |
      #!/usr/bin/env python
      from bottle import get, run, abort
      from subprocess import check_output
      from socket import gethostname
      from signal import signal, setitimer, ITIMER_REAL, SIGALRM

      def cleanup(signum, frame):
          try:
              nodes = check_output('docker node ls', shell=True).strip()
              down = map(lambda x: x.split()[1], filter(lambda x: 'Down' in x, nodes.split("\n")))
              for node in down:
                  check_output('docker node rm ' + node, shell=True)
          except:
              pass

      @get("/join/worker")
      def token():
          return check_output('docker swarm join-token -q worker', shell=True).strip()

      @get("/join/master")
      def token():
          return check_output('docker swarm join-token -q master', shell=True).strip()
      
      @get("/drain/<hostname>")
      def drain(hostname):
          try:
              return check_output('docker node update --availability drain ' + hostname, shell=True).strip()
          except:
              abort(404, "node not found")
        
      if gethostname() == 'master0':
          try:
              check_output('docker swarm init', shell=True)
          except:
              pass
          signal(SIGALRM, cleanup)
          setitimer(ITIMER_REAL, 10, 10)
          run(port=1337,host='0.0.0.0')
  - path: /etc/systemd/system/swarm-helper.service
    permissions: 0444
    content: |
      [Unit]
      Description=Swarm Helper
      DefaultDependencies=no
      After=multi-user.target
      [Service]
      Type=oneshot
      ExecStart=/root/swarm-helper.py
      [Install]
      WantedBy=multi-user.target
  - path: /root/mount-fileshare.sh
    permissions: 0755
    content: |
      #!/bin/bash
      # Create the fathom mount point if necessary and mount the file share
      sudo mkdir -p /fathom
      sudo mount -t cifs //swarmdemostore.file.core.windows.net/swarm-demo-fileshare /fathom -o vers=3.0,user=swarmdemostore,password=hFlNNLV5HavxqyMd8IlVutRpScHxyPzBpN/y3oqFEFIQ5ir9FGZGxnwOKSUbNQAL7/zS0RDI2S92qDEovm+Q5A==,dir_mode=0777,file_mode=0777
  - path: /etc/systemd/system/fathom-mount.service
    permissions: 0444
    content: |
      [Unit]
      Description=Mount Fathom file share
      DefaultDependencies=no
      Before=multi-user.target
      [Service]
      Type=oneshot
      ExecStart=/root/mount-fileshare.sh
      [Install]
      WantedBy=multi-user.target

apt:
  sources:
    docker.list:
      source: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
      keyserver: p80.pool.sks-keyservers.net
      keyid: 58118E89F3A912897C070ADBF76221572C52609D

apt_update: true
#apt_upgrade: true

packages:
  - ntp
  - docker-engine
  - tmux
  - htop
  - vim
  - fail2ban
  - curl
  - python-bottle
  - apt-file

runcmd:
  - usermod -G docker cluster
  - systemctl enable fathom-mount
  - systemctl start fathom-mount
  - systemctl enable nvidia-docker
  - systemctl start nvidia-docker
  - systemctl enable swarm-helper
  - systemctl start swarm-helper
#- reboot
